<?php

return [
    'InfoBip'                    => ['fqn' =>'InfoBipProviderRepository', 'location' => 'https://google.com', 'supported' => true],
    'AmazonAws'                  => ['fqn' =>'AmazonSnsProviderRepository', 'location' => 'https://google.com', 'supported' => true],
    'BulkGate'                   => ['fqn' =>'BulkGateProviderRepository', 'location' => 'https://google.com', 'supported' => true],
    'BulkSms'                    => ['fqn' =>'BulkSmsProviderRepository', 'location' => 'https://google.com', 'supported' => false],    
    'BurstSms'                   => ['fqn' =>'BurstSmsProviderRepository', 'location' => 'https://google.com', 'supported' => true],
    'MessageBird'                => ['fqn' =>'MessageBirdProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'OneS2U'                     => ['fqn' =>'OneS2UProviderRepository', 'location' => 'https://google.com', 'supported' => true],
    'SmsGlobal'                  => ['fqn' =>'SmsGlobalProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'SmsSmart'                   => ['fqn' =>'SmsSmartProviderRepository', 'location' => 'https://google.com', 'supported' => true],
    'TextBelt'                   => ['fqn' =>'TextBeltProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Twilio'                     => ['fqn' =>'TwilioProviderRepository', 'location' => 'https://google.com', 'supported' => true],
    'Nexmo (Vonage)'             => ['fqn' =>'NexmoProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Plivo'                      => ['fqn' =>'PlivoProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Sinch'                      => ['fqn' =>'SinchProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'SendPulse'                  => ['fqn' =>'SendPulseProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Telesign'                   => ['fqn' =>'TelesignProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'ClickSend'                  => ['fqn' =>'ClickSendProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Sendinblue'                 => ['fqn' =>'SendinBlueProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Bandwidth'                  => ['fqn' =>'BandWidthProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Clickatell'                 => ['fqn' =>'ClickatellProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Routee'                     => ['fqn' =>'RouteeProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Kaleyra'                    => ['fqn' =>'KaleyraProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Voximplant'                 => ['fqn' =>'VoxImplantProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Red Oxygen'                 => ['fqn' =>'RedOxygenProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'SMSSync'                    => ['fqn' =>'SmsSyncProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Gupshup'                    => ['fqn' =>'GupShupProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Mitto'                      => ['fqn' =>'MittoProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Termii'                     => ['fqn' =>'TermiiProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'TextMagic'                  => ['fqn' =>'TextMagicProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'iSMS'                       => ['fqn' =>'iSmSProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'MSG91'                      => ['fqn' =>'Msg91ProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Messente'                   => ['fqn' =>'MessenteProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'D7 Networks'                => ['fqn' =>'D7NetworkProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Wavecell'                   => ['fqn' =>'WaveCellProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Comilio'                    => ['fqn' =>'ComilioProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'TeleSign'                   => ['fqn' =>'TelesignProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Esendex'                    => ['fqn' =>'EsendexProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Spring Edge'                => ['fqn' =>'SpringEdgeProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'CM.com'                     => ['fqn' =>'CMProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Skebby'                     => ['fqn' =>'SkebbyProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Textlocal'                  => ['fqn' =>'TextLocalProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'TelecomsXChange'            => ['fqn' =>'TelecomsXChangeProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Silverstreet'               => ['fqn' =>'SilverStreetProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Notifyre'                   => ['fqn' =>'NotifyreProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Africa\'s Talking'          => ['fqn' =>'AfricasTalkingProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'TxtNation'                  => ['fqn' =>'TxtNationProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Dialog SMS'                 => ['fqn' =>'DialogSmsProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Vyke'                       => ['fqn' =>'VykeProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
    'Tata Tele Business Services'=> ['fqn' =>'TataBusinessProviderRepository', 'location' => 'https://google.com', 'supported' => true],    
];